### ISSUE TITLE
Problem checkPassword

### ISSUE THREAD

**Issue by codingjeremy** [android/security-samples#10]
<a href="https://github.com/moisesvs"><img src="https://avatars3.githubusercontent.com/u/611586?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [moisesvs](https://github.com/moisesvs)**
_Friday Dec 11, 2015 at 10:36 GMT_
_Originally opened as https://github.com/googlesamples/android-FingerprintDialog/issues/23_

----

I am checking the source code of the fingerprintDialog and I saw the method checkPassword in the FingerprintAuthenticationDialogFragment class but this method isn't working because only checked if the password isn't empty and nothing else. 

My question is: This method should check the pin code of the phone, no?

Regards

**Comment by codingjeremy** [comment]
<a href="https://github.com/thagikura"><img src="https://avatars2.githubusercontent.com/u/796361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [thagikura](https://github.com/thagikura)**
_Friday Jan 29, 2016 at 04:59 GMT_

----

Hi, 

It may be a belated reply, but the checkPassword method in the FingerprintDialog is meant to check the app specific password for the user instead of the pin code of the phone.

If you want to check the pin code of the phone, you can use `KeyguardManager.createDeviceCredentialIntent`.

**Comment by isaidamier** [comment]
Please refer to the new sample https://github.com/android/security-samples/tree/master/BiometricLoginKotlin
