### ISSUE TITLE
Build Failed with dagger

### ISSUE THREAD

**Issue by codingjeremy** [android/security-samples#11]
<a href="https://github.com/AkashMen10"><img src="https://avatars0.githubusercontent.com/u/18595082?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [AkashMen10](https://github.com/AkashMen10)**
_Thursday Apr 21, 2016 at 12:15 GMT_
_Originally opened as https://github.com/googlesamples/android-FingerprintDialog/issues/27_

----

Build failed with below error:
Error:(43, 9) error: cannot find symbol method library()
Error:(44, 9) error: cannot find symbol method injects()
Error:(44, 19) error: illegal initializer for <none>
Error:Execution failed for task ':compileDebugJavaWithJavac'.

> Compilation failed; see the compiler error output for details.

**Comment by isaidamier** [comment]
Please refer to the new sample https://github.com/android/security-samples/tree/master/BiometricLoginKotlin
