### ISSUE TITLE
crash after emulator reboot

### ISSUE THREAD

**Issue by codingjeremy** [android/security-samples#14]
<a href="https://github.com/Ghostish"><img src="https://avatars0.githubusercontent.com/u/7406087?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Ghostish](https://github.com/Ghostish)**
_Monday Aug 01, 2016 at 01:49 GMT_
_Originally opened as https://github.com/googlesamples/android-FingerprintDialog/issues/33_

----

I was testing the sample app at Nexux 5x emulator. 
When I restart the app after rebooting the emulator, it crashed. 

In android monitor it read:

> java.lang.RuntimeException: java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use

That's so weird . I checked the return value of `mFingerprintManager.hasEnrolledFingerprints()` ,which was true.  But the exception still was thrown during the `createKey()` .

**Comment by codingjeremy** [comment]
<a href="https://github.com/kdhiren"><img src="https://avatars0.githubusercontent.com/u/25608893?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kdhiren](https://github.com/kdhiren)**
_Tuesday Feb 07, 2017 at 10:44 GMT_

----

i face the same problem.

**Comment by codingjeremy** [comment]
<a href="https://github.com/yakivmospan"><img src="https://avatars2.githubusercontent.com/u/1574033?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yakivmospan](https://github.com/yakivmospan)**
_Sunday Sep 24, 2017 at 11:49 GMT_

----

Still exists on emulate API 23, x86, 10th revision.

**Comment by isaidamier** [comment]
Please refer to the new sample and feel free to reopen if the issue persists https://github.com/android/security-samples/tree/master/BiometricLoginKotlin
