### ISSUE TITLE
How i insert the fingerprint in emulator if using window.

### ISSUE THREAD

**Issue by codingjeremy** [android/security-samples#17]
<a href="https://github.com/terrancelaw93"><img src="https://avatars0.githubusercontent.com/u/21198049?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [terrancelaw93](https://github.com/terrancelaw93)**
_Tuesday Sep 06, 2016 at 04:49 GMT_
_Originally opened as https://github.com/googlesamples/android-FingerprintDialog/issues/36_

----

**Comment by isaidamier** [comment]
Hi, we are reserving this site for questions about the sample apps specifically. For more general questions about Biometrics on Android, please use [StackOverflow with tag android-biometric](https://stackoverflow.com/questions/tagged/android-biometric).

Also this sample is being deprecated in favor of [BiometricLoginKotlin](https://github.com/android/security-samples/tree/biometriclogin)
