### ISSUE TITLE
CRASH: on save instance state exception 

### ISSUE THREAD

**Issue by codingjeremy** [android/security-samples#18]
<a href="https://github.com/br00"><img src="https://avatars1.githubusercontent.com/u/4648706?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [br00](https://github.com/br00)**
_Wednesday Oct 12, 2016 at 07:50 GMT_
_Originally opened as https://github.com/googlesamples/android-FingerprintDialog/issues/39_

----

Hi,
To make it crash do this:
- authenticate with your finger
- the animation with "Fingerprint recognised" text is shown
- because that animation has 1 sec of delay before calling the callback mCallback.onAuthenticated();
- if you send the app in background during the animation then it crash (just press home button before the animation is gone)

The issue is that are missing some checks when you call dismiss()

 @Override
    public void onAuthenticated() {
        // Callback from FingerprintUiHelper. Let the activity know that authentication was
        // successful.
        mActivity.onPurchased(true /\* withFingerprint */, mCryptoObject);
        dismiss();
    }

I suggest to put
Activity anActivity = getActivity();
if (getDialog() != null && getDialog().isShowing() && isResumed() && anActivity != null && !anActivity.isFinishing()) {
    dismiss();
}

or you can use dismissAllowingStateLoss()

**Comment by codingjeremy** [comment]
<a href="https://github.com/usantos"><img src="https://avatars0.githubusercontent.com/u/124369?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [usantos](https://github.com/usantos)**
_Thursday Jul 04, 2019 at 20:05 GMT_

----

If you use dismissAllowingStateLoss ()
would it be after the dismiss?

**Comment by nic0lette** [comment]
The sample was ported to use BiometricPrompt and so I'm hopeful that this issue would be resolved. If it's still occurring, please open another issue.
