### ISSUE TITLE
UserNotAuthenticatedException: User not authenticated

### ISSUE THREAD

**Issue by codingjeremy** [android/security-samples#20]
<a href="https://github.com/repitch"><img src="https://avatars3.githubusercontent.com/u/9460725?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [repitch](https://github.com/repitch)**
_Thursday Nov 03, 2016 at 09:09 GMT_
_Originally opened as https://github.com/googlesamples/android-FingerprintDialog/issues/41_

----

Problem appears only on some devices:

- Meizu PRO 6
- HTC One M9PLUS (M9+)
- LeTV Le 1s X500

Location:
`MainActivity#initCipher(Cipher cipher, String keyName)`
line 165
when calling `cipher.init(Cipher.ENCRYPT_MODE, key);`
i got `android.security.keystore.UserNotAuthenticatedException: User not authenticated`

**Comment by codingjeremy** [comment]
<a href="https://github.com/vijayjangid07"><img src="https://avatars0.githubusercontent.com/u/1968789?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vijayjangid07](https://github.com/vijayjangid07)**
_Wednesday Feb 15, 2017 at 12:40 GMT_

----

I am also facing the same issue in HTC One M9PLUS.
@repitch Did you find the solution for the same.

**Comment by codingjeremy** [comment]
<a href="https://github.com/sickworm"><img src="https://avatars3.githubusercontent.com/u/2757460?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sickworm](https://github.com/sickworm)**
_Thursday May 04, 2017 at 10:50 GMT_

----

me too, it seems get into a dead loop.

authenticate needs init, init needs authenticate

BTW, asymmetric key works fine, just the problem of symmetric key

**Comment by codingjeremy** [comment]
<a href="https://github.com/axelwerner"><img src="https://avatars2.githubusercontent.com/u/8915115?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [axelwerner](https://github.com/axelwerner)**
_Wednesday Apr 11, 2018 at 15:54 GMT_

----

I have also the problem on asymmetric key :(
If I configure my KeyGenerator like this,

                KeyGenParameterSpec spec = new KeyGenParameterSpec.Builder(alias, KeyProperties.PURPOSE_ENCRYPT | KeyProperties.PURPOSE_DECRYPT)
                        .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_RSA_PKCS1)
                        .setKeySize(4096)
                        .setUserAuthenticationRequired(true)
                        .setUserAuthenticationValidityDurationSeconds(6 * 10)
                        .build();

**Comment by codingjeremy** [comment]
<a href="https://github.com/mlynch"><img src="https://avatars3.githubusercontent.com/u/11214?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mlynch](https://github.com/mlynch)**
_Friday Jun 01, 2018 at 17:59 GMT_

----

Running into this as well, seems to get stuck in an auth loop occasionally . Anyone able to get around it? This is for generating an asymmetric key

**Comment by codingjeremy** [comment]
<a href="https://github.com/NasH5169"><img src="https://avatars2.githubusercontent.com/u/6979479?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [NasH5169](https://github.com/NasH5169)**
_Tuesday Jul 24, 2018 at 08:33 GMT_

----

Same on Huawei ALE-L21. Seems to be related to the duration..? If the setUserAuthenticationValidityDurationSeconds is huge value like 30000, it's ok... Very strange.

**Comment by codingjeremy** [comment]
<a href="https://github.com/KimJinRyul"><img src="https://avatars2.githubusercontent.com/u/6406569?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [KimJinRyul](https://github.com/KimJinRyul)**
_Monday Aug 06, 2018 at 11:18 GMT_

----

I am also experiencing the same issue.
This problem occurs when setUserAuthenticationValidityDurationSeconds is used.
It seems to happen when the screen unlocked time is older than specified time.

for example.. when I set 5 secs... It failed.....
but try again within 5secs after I unlock the screen... It will pass...

**Comment by codingjeremy** [comment]
<a href="https://github.com/yashasvigirdhar"><img src="https://avatars1.githubusercontent.com/u/2319525?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yashasvigirdhar](https://github.com/yashasvigirdhar)**
_Sunday Nov 25, 2018 at 09:58 GMT_

----

@KimJinRyul , this is the expected behaviour of the api

**Comment by codingjeremy** [comment]
<a href="https://github.com/nioncode"><img src="https://avatars0.githubusercontent.com/u/3159451?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nioncode](https://github.com/nioncode)**
_Saturday Jul 27, 2019 at 18:34 GMT_

----

When using `setUserAuthenticationValidityDurationSeconds`, do NOT pass a `CryptoObject` to `BiometricPrompt.authenticate`. Instead, simply attempt the cryptographic operation (including `Cipher.init`) and catch `UserNotAuthenticatedException`. When you catch the exception, show the `BiometricPrompt` and initialize the Cipher in the `onAuthenticationSucceeded` from scratch.

You only have to pass a `CryptoObject` to `BiometricPrompt.authenticate` if you do not use `setUserAuthenticationValidityDurationSeconds`, because then the user must be authenticated through the prompt for each access.

**Comment by FrmldrDD** [comment]
I have the same issue. I followed your hints @codingjeremy but I still get `UserNotAuthenticatedException` within `override fun onAuthenticationSucceeded(result: BiometricPrompt.AuthenticationResult)` when I try to initialize the cipher there.

Unfortunately, I was not able to reproduce the issue on my side, only by other users in wildlife reported via Crashlytics.

Any ideas?

**Comment by isaidamier** [comment]
This sample is being deprecated in favor of [BiometricLoginKotlin](https://github.com/android/security-samples/tree/biometriclogin)
