### ISSUE TITLE
Can realize the function of fingerprint puncher

### ISSUE THREAD

**Issue by codingjeremy** [android/security-samples#22]
<a href="https://github.com/zrtian"><img src="https://avatars3.githubusercontent.com/u/3364887?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zrtian](https://github.com/zrtian)**
_Wednesday Dec 21, 2016 at 07:55 GMT_
_Originally opened as https://github.com/googlesamples/android-FingerprintDialog/issues/43_

----

Can realize the function of fingerprint puncher

**Comment by codingjeremy** [comment]
<a href="https://github.com/zrtian"><img src="https://avatars3.githubusercontent.com/u/3364887?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zrtian](https://github.com/zrtian)**
_Wednesday Dec 21, 2016 at 08:18 GMT_

----

利用指纹sdk，可以将某些指纹信息与指定的账号信息进行绑定吗，类似与指纹打卡的功能？

**Comment by isaidamier** [comment]
Hi, we are reserving this site for questions about the sample apps specifically. For more general questions about Biometrics on Android, please use [StackOverflow with tag android-biometric](https://stackoverflow.com/questions/tagged/android-biometric).

Also this sample is being deprecated in favor of [BiometricLoginKotlin](https://github.com/android/security-samples/tree/biometriclogin)
