### ISSUE TITLE
Role of cryptoObject

### ISSUE THREAD

**Issue by codingjeremy** [android/security-samples#25]
<a href="https://github.com/yashasvigirdhar"><img src="https://avatars1.githubusercontent.com/u/2319525?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yashasvigirdhar](https://github.com/yashasvigirdhar)**
_Tuesday Jun 06, 2017 at 07:14 GMT_
_Originally opened as https://github.com/googlesamples/android-FingerprintDialog/issues/46_

----

After going through the sample,

I am still curious about what is the use of passing `cryptoObject` to `authenticate` api of `FingerprintManager`.

If we see the code [here](http://androidxref.com/7.1.1_r6/xref/frameworks/base/core/java/android/hardware/fingerprint/FingerprintManager.java#477), it stores the reference to `cryptoObject` in a field which it uses only at one place : to create the `AuthenticationResult` when authenticatin succeeds (see [here](http://androidxref.com/7.1.1_r6/xref/frameworks/base/core/java/android/hardware/fingerprint/FingerprintManager.java#854)).

Also, apart from this, it uses the cryptoObject's `getOpId` method to set some `sessionId` that it passes to `authenticate` api of `IFingerprintService`. 

What's this `OpId`? I guess this is the thing that makes all difference, but I've no clue what it is and can't seem to find any documentation :-/ 

This question has been asked [here](https://stackoverflow.com/questions/44327885/android-fingerprint-authentication-role-of-cryptoobject), [here](https://stackoverflow.com/questions/34754889/android-cryptoobject-usage-in-fingerprint) and [here](https://stackoverflow.com/questions/34754889/android-cryptoobject-usage-in-fingerprint) but I didn't find a good answer in all the places.

**Comment by isaidamier** [comment]
You should find the answer [here](https://medium.com/androiddevelopers/using-biometricprompt-with-cryptoobject-how-and-why-aace500ccdb7)
