### ISSUE TITLE
Android Enterprise app not detecting any fingerprints

### ISSUE THREAD

**Issue by codingjeremy** [android/security-samples#27]
<a href="https://github.com/ruscles"><img src="https://avatars3.githubusercontent.com/u/11840925?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ruscles](https://github.com/ruscles)**
_Monday Jul 03, 2017 at 14:18 GMT_
_Originally opened as https://github.com/googlesamples/android-FingerprintDialog/issues/48_

----

Hi,

I have an app that is developed to run inside the Android Enterprise container (for corporate devices). The fingerprint authentication from this sample works perfectly when the app is installed **outside** the enterprise container. However, when the app is running **inside** the container, it is unable to detect any fingerprints that the user registered outside the container (on the normal device).

It fails at this piece (line 137 of MainActivity):
```
if (!fingerprintManager.hasEnrolledFingerprints()) {
            // User hasn't enrolled any fingerprints to authenticate with
            Toast.makeText(this, "Go to 'Settings -> Security -> Fingerprint' and register at least one fingerprint", Toast.LENGTH_LONG).show();
            return;
        }
```

Is there a way to detect registered fingerprints outside the Enterprise container from an app that is running inside the container? I have tested this on an S7, S8, and Pixel. Thanks!

**Comment by saqibmirza2007** [comment]
@codingjeremy Android enterprise have different setting for Biometric and you have to enroll separate Biometrics there. The settings depend on vendor and device
