### ISSUE TITLE
No Fingerprints in Device

### ISSUE THREAD

**Issue by codingjeremy** [android/security-samples#35]
<a href="https://github.com/Lavanya-Kasina"><img src="https://avatars1.githubusercontent.com/u/13230900?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Lavanya-Kasina](https://github.com/Lavanya-Kasina)**
_Tuesday Mar 26, 2019 at 11:16 GMT_
_Originally opened as https://github.com/googlesamples/android-FingerprintDialog/issues/56_

----

Is there any way to authenticate with device password when no fingerprints are present.

**Comment by isaidamier** [comment]
Hi Lavanya-Kasina,

Would you please post this question on StackOverflow? For general usage, implementation, or integration questions, please post on StackOverflow -- we are actively tracking questions there. Use the tag android-biometric. Thanks!
