### ISSUE TITLE
Issue with the app

### ISSUE THREAD

**Issue by codingjeremy** [android/security-samples#36]
<a href="https://github.com/ravi6342"><img src="https://avatars2.githubusercontent.com/u/50036004?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ravi6342](https://github.com/ravi6342)**
_Tuesday Jul 16, 2019 at 13:14 GMT_
_Originally opened as https://github.com/googlesamples/android-FingerprintDialog/issues/57_

----

The app is not running on the device which does't have a fingerprint sensor. The app is crashing when i try to authenticate with the password and at the same time the password entered by me is not matching the system password and is letting me in the app with any letters.

**Comment by isaidamier** [comment]
This app is being deprecated in favor of [BiometricLoginKotlin](https://github.com/android/security-samples/tree/biometriclogin)
