### ISSUE TITLE
KeyPermanentlyInvalidatedException not thrown all the time after enrolling new fingerprint

### ISSUE THREAD

**Issue by codingjeremy** [android/security-samples#9]
<a href="https://github.com/TheNephilim88"><img src="https://avatars0.githubusercontent.com/u/1174584?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [TheNephilim88](https://github.com/TheNephilim88)**
_Monday Nov 30, 2015 at 20:18 GMT_
_Originally opened as https://github.com/googlesamples/android-FingerprintDialog/issues/21_

----

The initCipher()-method checks if lockscreen has been disabled or new fingerprints have been enrolled.
For this it checks if a KeyPermanentlyInvalidatedException will be thrown or not. If it wil lbe thrown, any of above reasons apply.

But this does not seem to trigger all the time. It only triggers randomly on my device (Nexus 5X) after adding new fingerprints.
Most of the time I get normal fingerprint-authentication dialog and it works as nothing has been changed. Only very few times I get "A new fingerprint was added to this device"-message to reauthenticate.

Can anyone tell me why this is not triggering all the time when new fingerprints have been enrolled? Is this a bug or a feature? :D 

Is it possible to check for fingerprint-changes in another way?

**Comment by codingjeremy** [comment]
<a href="https://github.com/thagikura"><img src="https://avatars2.githubusercontent.com/u/796361?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [thagikura](https://github.com/thagikura)**
_Monday Dec 07, 2015 at 03:48 GMT_

----

Hi,

Detecting a new fingerprint is not triggered randomly.
One thing I'm guessing is that you may have created a new key after new fingerprints were added.

This sample creates a new key in onCreate, so if you launch the sample app after you add a new fingerprint, KeyPermanentlyInvalidatedException is not thrown because at the time the key is created, a set of fingerprints include the new created one.

If you want to test that KeyPermanentlyInvalidatedException, please try to add a new fingerprint while  keeping the app open.

**Comment by codingjeremy** [comment]
<a href="https://github.com/tajchert"><img src="https://avatars3.githubusercontent.com/u/2962633?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tajchert](https://github.com/tajchert)**
_Friday Oct 06, 2017 at 11:11 GMT_

----

Also this is a case for me - I get (API 26 both emulator and Nexus 5x) `IllegalBlockSizeException` instead of `KeyPermanentlyInvalidatedException` after adding new imprint.

**Comment by codingjeremy** [comment]
<a href="https://github.com/tajchert"><img src="https://avatars3.githubusercontent.com/u/2962633?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tajchert](https://github.com/tajchert)**
_Monday Oct 09, 2017 at 15:42 GMT_

----

I believe this is the reason of this issue: https://issuetracker.google.com/issues/65578763

**Comment by Morteza-Rastgoo** [comment]
So to avoid creating a new key, how to load previous key?
